### ISSUE TITLE
epiConv Installation Error (Segmentation Fault)

### ISSUE THREAD

**Issue by KMt9WT** [LiLin-biosoft/epiConv#1]
Hello.

I followed the epiConv Installation to install the matrix_sum command and I have created the matrix_sampl command,   
but the The execution error occurred and I would like to hear how to deal with it.

---
The OS that performed the installation was CentOS7.6 (do I need CentOS6.9?). 
I installed the following application on my operating system and set up its execution path: 
````
perl 5.16.3
bedtools v2.27.1
MACS2 2.3.1.1
R 3.5.1 with Matrix, bigmemory, biganalytics, umap, PRIMME, densityClust, heatmap.plus
````

I ran the following commands to compile the file (no errors or warnings at compile time)

````
The version of gcc is 4.8.5.
g++ -Wall ~/epiConv/matrix_sum.c -o ~/epiConv/ matrix_sum
g++ -Wall ~/epiConv/matrix_sampl.c -o ~/epiConv /matrix_sampl
````

But a Segmentation Fault error occurred when executing the binary file.

```
$ . /matrix_sum 
Segmentation fault (core dumped)

$ . /matrix_sampl
Segmentation fault (core dumped)
````

I tried to compile it in gcc (it's not gcc, but g++ Do you need to?)
The following error message was printed.
```
$ gcc -Wall matrix_sampl.c -o matrix_sampl                 
matrix_sampl.c: In function 'retain2uppertri':
matrix_sampl.c:14:26: warning: argument to ' sizeof' in 'memset' call is the same expression as the destination; did you mean to dereference it? Wsizeof-pointer-memaccess]
  memset(uppertri,0,sizeof(uppertri));
                          ^
matrix_sampl.c: In function 'main':
matrix_sampl.c:90:29: error: 'cmm' undeclared ( First use in this function)
  while(fread(&record,sizeof(cmm),1,cmat)! =0){
                             ^~~
matrix_sampl.c:90:29: note: each undeclared identifier is reported only once for each function It appears in

---

$ gcc -Wall matrix_sum.c -o matrix_sum                                                   
matrix_sum.c: In function ‘main’:
matrix_sum.c:37:26: error: ‘cmm’ undeclared (first use in this function)
      fwrite(&temp,sizeof(cmm),1,out);
                          ^
matrix_sum.c:37:26: note: each undeclared identifier is reported only once for each function it appears in
matrix_sum.c:59:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
````

If you have any suggestions on how to deal with this, I would appreciate it.

Thanks.

**Comment by LiLin-biosoft** [comment]
Hello，
For now, there are no helping messages in the script. So if no input file is specified, the script will break.  I'm sorry about that. I think you can prepare some small input files to see whether epiConv works properly. Moreover, given the full version is slow and always generates similar results with simplified version, we may remove the full version in the near future. If some errors still occur, you can just try simplified version.

**Comment by KMt9WT** [comment]
Thanks for the reply.

I got the same error when I ran the full version using the input file.
I would like to use the simplified version for now.

Mizotani
